# Generated by Django 4.0.2 on 2022-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tva_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tva_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('web', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
